#!/usr/bin/env sh

#  helper script: modify coreboot configs (run make menuconfig)
#
#	Copyright (C) 2021, 2023 Leah Rowe <info@minifree.org>
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>.

[ "x${DEBUG+set}" = 'xset' ] && set -v
set -u -e

main()
{
	printf "Updating seabios configs\n"
	download_seabios
	modify_configs
}

download_seabios()
{
	if [ ! -d "seabios" ]; then
		./download seabios
	fi
	if [ ! -d "seabios" ]; then
		printf "error: Failed to download SeaBIOS. "
		printf "Check internet connection?\n"
		exit 1
	fi
}

modify_configs()
{
	for config in resources/seabios/config/*; do
		if [ ! -f "${config}" ]; then
			continue
		fi
		make distclean -BC seabios
		mv "${config}" seabios/.config
		make menuconfig -BC seabios
		cp seabios/.config "${config}"
		make distclean -BC seabios
	done
}

main $@
