#!/usr/bin/env sh

#
#  helper script: update coreboot configs (run make oldconfig)
#
#	Copyright (C) 2021 Leah Rowe <info@minifree.org>
#	Copyright (C) 2022 Ferass El Hafidi <vitali64pmemail@protonmail.com>
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# This script assumes that the working directory is the root
# of git or release archive

[ "x${DEBUG+set}" = 'xset' ] && set -v
set -u -e

cbcfgsdir="resources/coreboot"

main()
{
	printf "Updating coreboot configs\n"

	if [ $# -gt 0 ]; then
		for board in "${@}"; do
			updateconf "${board}"
		done
	else
		for board in ${cbcfgsdir}/*; do
		if [ ! -d "${board}" ]; then
			continue
		fi
			updateconf "${board##*/}"
		done
	fi
}

# Build ROM images for supported boards
updateconf()
{
	board=${1}

	boarddir="${cbcfgsdir}/${board}"

	if [ -f "${boarddir}/board.cfg" ]; then
		cbtree="undefined"
		. "${boarddir}/board.cfg" # source
		if [ "${cbtree}" = "undefined" ]; then
			return 0
		fi
		cbdir="coreboot/${cbtree}"
		if [ ! -d "${cbdir}" ]; then
			./download coreboot ${cbtree}
		fi
		for cbcfg in "${boarddir}/config/"*; do
			if [ ! -f "${cbcfg}" ]; then
				continue
			fi
			make distclean -BC "${cbdir}"
			mv $cbcfg ${cbdir}/.config
			make oldconfig -BC "${cbdir}"
			mv ${cbdir}/.config $cbcfg
			make distclean -BC "${cbdir}"
		done
	else
		printf "\nupdate/config/coreboot: no board.cfg for: %s\n" \
				${board}
	fi
}

main $@
