#!/usr/bin/env sh

#  helper script: modify coreboot configs (run make menuconfig)
#
#	Copyright (C) 2021, 2023 Leah Rowe <info@minifree.org>
#	Copyright (C) 2022 Ferass El Hafidi <vitali64pmemail@protonmail.com>
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

[ "x${DEBUG+set}" = 'xset' ] && set -v
set -u -e

main()
{
	printf "Modifying coreboot configs\n"

	if [ $# -gt 0 ]; then
		for board in ${@}; do
			modifyconf "${board}"
		done
	else
		for board in resources/coreboot/*; do
			if [ ! -d "${board}" ]; then
				continue
			fi
			modifyconf "${board##*/}"
		done
	fi
}

# Build ROM images for supported boards
modifyconf() {
	board="$1"

	if [ ! -f "resources/coreboot/${board}/board.cfg" ]; then
		printf "\nmodify/config/coreboot: no board.cfg for: %s\n" \
				"${board}"
	fi

	cbtree=""
	. "resources/coreboot/${board}/board.cfg" # source

	if [ -z ${cbtree} ]; then
		return 0
	fi
	cbdir="coreboot/${cbtree}"
	if [ ! -d "${cbdir}" ]; then
		./download coreboot ${cbtree}
	fi

	for cbcfg in resources/coreboot/${board}/config/*; do
		if [ ! -f ${cbcfg} ]; then
			continue
		fi
		make distclean -BC "${cbdir}"
		mv "${cbcfg}" "${cbdir}/.config"
		make menuconfig -BC "${cbdir}"
		mv "${cbdir}/.config" "${cbcfg}"
		make distclean -BC "${cbdir}"
	done
}

main $@
