#!/usr/bin/env bash

#  helper script: downloads flashrom and patches it
#
#	Copyright (C) 2014, 2015, 2020, 2021 Leah Rowe <info@minifree.org>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

[ "x${DEBUG+set}" = 'xset' ] && set -v
set -u -e

usage()
{
	progname="./download flashrom"
	printf "Usage:\n"
	printf "\t%s         # %s\n" \
	       "${progname}" \
	       "Download flashrom"
	printf "\t%s --help  # %s\n" \
	       "${progname}" \
	       "Prints this help"
}

if [ $# -ne 0 ] ; then
	usage
	exit 0
fi

# Get flashrom at the last previously tested revision

# Remove the old version that may still exist:
# ------------------------------------------------------------------------------

printf "Downloading flashrom\n"

rm -Rf "flashrom/"

# Get flashrom
# ------------------------------------------------------------------------------

# download it using git
git clone https://review.coreboot.org/flashrom.git

if [ ! -d "flashrom" ]; then
    printf "flashrom not downloaded; check network connection?\n\n"
    exit 1
fi

(
cd "flashrom/"

# reset to known revision
git reset --hard 11680db4e1251eb842bee11e53b6d1f0ae67767b
)

printf "\n\n"
