#!/usr/bin/env sh

# SPDX-FileCopyrightText: 2022 Caleb La Grange <thonkpeasant@protonmail.com>
# SPDX-FileCopyrightText: 2022 Ferass El Hafidi <vitali64pmemail@protonmail.com>
# SPDX-FileCopyrightText: 2023 Leah Rowe <info@minifree.org>
# SPDX-License-Identifier: GPL-3.0-only

. "include/err.sh"

sname=""
archive=""
_filetype=""
rom=""
board=""
modifygbe=""
new_mac=""
release=""
releasearchive=""

cbdir="coreboot/default"
cbcfgsdir="resources/coreboot"
ifdtool="cbutils/default/ifdtool"
cbfstool="cbutils/default/cbfstool"
nvmutil="util/nvmutil/nvm"
boarddir=""
pciromsdir="pciroms"

CONFIG_HAVE_MRC=""
CONFIG_HAVE_ME_BIN=""
CONFIG_ME_BIN_PATH=""
CONFIG_KBC1126_FIRMWARE=""
CONFIG_KBC1126_FW1=""
CONFIG_KBC1126_FW1_OFFSET=""
CONFIG_KBC1126_FW2=""
CONFIG_KBC1126_FW2_OFFSET=""
CONFIG_VGA_BIOS_FILE=""
CONFIG_VGA_BIOS_ID=""
CONFIG_GBE_BIN_PATH=""
CONFIG_INCLUDE_SMSC_SCH5545_EC_FW=""
CONFIG_SMSC_SCH5545_EC_FW_FILE=""

main()
{
	sname="${0}"

	[ $# -lt 1 ] && err "No options specified."
	[ "${1}" = "listboards" ] && listboards && exit 0

	archive="${1}"

	while getopts r:b:m: option
	do
		case "${option}" in
		r)
			rom=${OPTARG} ;;
		b)
			board=${OPTARG} ;;
		m)
			modifygbe=true
			new_mac=${OPTARG} ;;
		esac
	done

	check_board
	build_dependencies
	inject_blobs

	printf "Friendly reminder (this is *not* an error message):\n"
	printf "Please always ensure that the files were inserted correctly.\n"
	printf "Read https://libreboot.org/docs/install/ivy_has_common.html\n"
}

check_board()
{
	if ! check_release ${archive} ; then
		[ -f "${rom}" ] || \
			err "${rom} is not a valid path"
		[ -z ${rom+x} ] && \
			err 'no rom specified'
		[ ! -z ${board+x} ] || \
			board=$(detect_board ${rom}) || \
			    err 'no board specified'
	else
		release=true
		releasearchive="${archive}"
		board=$(detect_board ${archive}) || \
		    err 'Could not detect board type'
	fi

	boarddir="${cbcfgsdir}/${board}"
	[ -d "${boarddir}" ] || err "board ${board} not found"
}

check_release()
{
	[ -f "${archive}" ] || return 1
	[ "${archive##*.}" = "xz" ] || return 1
	printf "%s\n" "Release archive ${archive} detected"
}

# This function tries to determine the board from the filename of the rom.
# It will only succeed if the filename is not changed from the build/download
detect_board()
{
	path=${1}
	filename=$(basename ${path})
	case ${filename} in
	grub_*)
		board=$(echo "${filename}" | cut -d '_' -f2-3) ;;
	seabios_withgrub_*)
		board=$(echo "${filename}" | cut -d '_' -f3-4) ;;
	*.tar.xz)
		_stripped_prefix=${filename#*_}
		board="${_stripped_prefix%.tar.xz}" ;;
	*)
		return 1
	esac	
	[ -d "${boarddir}/" ] || return 1
	printf '%s\n' "${board}"
}

build_dependencies()
{
	[ -d "${cbdir}" ] || ./fetch_trees coreboot default
	./build coreboot utils default || err "could not build cbutils"
	./update blobs download ${board} || \
	    err "Could not download blobs for ${board}"
}

inject_blobs()
{
	if [ "${release}" = "true" ]; then
		echo 'patching release file'
		patch_release_roms
	else
		patch_rom ${rom}
	fi
}

patch_release_roms()
{
	_tmpdir=$(mktemp -d "/tmp/${board}_tmpXXXX")
	tar xf "${releasearchive}" -C "${_tmpdir}" || \
	err 'could not extract release archive'

	for x in ${_tmpdir}/bin/*/*.rom ; do
		echo "patching rom $x"
		patch_rom ${x} || err "could not patch ${x}"
	done

	(
	cd ${_tmpdir}/bin/*
	sha1sum --status -c blobhashes || \
	err 'ROMs did not match expected hashes'
	)

	if [ "${modifygbe}" = "true" ]; then
		for x in ${_tmpdir}/bin/*/*.rom ; do
			modify_gbe ${x}
		done
	fi

	[ -d bin/release ] || mkdir -p bin/release
	mv ${_tmpdir}/bin/* bin/release/ && \
	    printf '%s\n' 'Success! Your ROMs are in bin/release'

	rm -r "${_tmpdir}"
}

patch_rom()
{
	rom="${1}"

	set -- "${boarddir}/config/"*
	. ${1} 2>/dev/null
	. "${boarddir}/target.cfg"

	[ "$CONFIG_HAVE_MRC" = "y" ] && \
		inject_blob_intel_mrc "${rom}"
	[ "${CONFIG_HAVE_ME_BIN}" = "y" ] && \
		inject_blob_intel_me "${rom}"
	[ "${CONFIG_KBC1126_FIRMWARE}" = "y" ] && \
		inject_blob_hp_kbc1126_ec "${rom}"
	[ "${CONFIG_VGA_BIOS_FILE}" != "" ] && \
	    [ "${CONFIG_VGA_BIOS_ID}" != "" ] && \
		inject_blob_dell_e6400_vgarom_nvidia
	[ "${CONFIG_INCLUDE_SMSC_SCH5545_EC_FW}" = "y" ] && \
	    [ "${CONFIG_SMSC_SCH5545_EC_FW_FILE}" != "" ] && \
		inject_blob_smsc_sch5545_ec "${rom}"
	[ "${modifygbe}" = "true" ] && ! [ "${release}" = "true" ] && \
		modify_gbe ${rom}
}

inject_blob_intel_mrc()
{
	rom="${1}"

	printf 'adding mrc\n'

	# mrc.bin must be inserted at a specific offset. the only
	# libreboot platform that needs it, at present, is haswell

	# in cbfstool, -b values above 0x80000000 are interpreted as
	# top-aligned x86 memory locations. this is converted into an
	# absolute offset within the flash, and inserted accordingly
	# at that offset into the ROM image file

	# coreboot's own build system hardcodes the mrc.bin offset
	# because there is only one correct location in memory, but
	# it would be useful for lbmk if it could be easily scanned
	# from Kconfig, with the option to change it where in practise
	# it is not changed

	# the hardcoded offset below is based upon reading of the coreboot
	# source code, and it is *always* correct for haswell platform.
	# TODO: this logic should be tweaked to handle more platforms

	${cbfstool} ${rom} add -f mrc/haswell/mrc.bin -n mrc.bin -t mrc \
		-b 0xfffa0000 || exit 1
}

inject_blob_intel_me()
{
	printf 'adding intel management engine\n'

	rom="${1}"
	[ -z ${CONFIG_ME_BIN_PATH} ] && \
		err "CONFIG_ME_BIN_PATH not set"

	_me_location=${CONFIG_ME_BIN_PATH#../../}
	[ ! -f "${_me_location}" ] && \
		err "CONFIG_ME_BIN_PATH points to missing file"

	${ifdtool} -i me:${_me_location} ${rom} -O ${rom} || exit 1
}

inject_blob_hp_kbc1126_ec()
{
	rom="${1}"

	_ec1_location="${CONFIG_KBC1126_FW1#../../}"
	_ec1_offset="${CONFIG_KBC1126_FW1_OFFSET}"
	_ec2_location="${CONFIG_KBC1126_FW2#../../}"
	_ec2_offset="${CONFIG_KBC1126_FW2_OFFSET}"

	printf "adding hp kbc1126 ec firmware\n"

	if [ "${_ec1_offset}" = "" ] || [ "${_ec1_offset}" = "" ]; then
		printf "EC offsets not declared for board: %s\n" \
		    "${board}"
		exit 1
	fi
	if [ "${_ec1_location}" = "" ] || [ "${_ec2_location}" = "" ]; then
		printf "EC firmware path not declared for board: %s\n" \
		    "${board}"
	fi
	if [ ! -f "${_ec1_location}" ] || [ ! -f "${_ec2_location}" ]; then
		printf "EC firmware not downloaded for board: %s\n" \
		    "${board}"
		exit 1
	fi

	${cbfstool} "${rom}" add -f ${_ec1_location} -n ecfw1.bin \
	    -b ${_ec1_offset} -t raw || exit 1
	${cbfstool} "${rom}" add -f ${_ec2_location} -n ecfw2.bin \
	    -b ${_ec2_offset} -t raw || exit 1
}

inject_blob_dell_e6400_vgarom_nvidia()
{
	rom="${1}"

	_vga_location="${CONFIG_VGA_BIOS_FILE#../../}"
	_vga_dir="${_vga_location%/*}"
	_vga_filename="${_vga_location##*/}"

	printf "adding pci option rom\n"

	if [ "${_vga_dir}" != "${pciromsdir}" ]; then
		printf "Invalid PCI ROM directory: %s\n" ${_vga_dir}
		exit 1
	fi
	if [ ! -f "${_vga_location}" ]; then
		printf "No such file exists: %s\n" ${_vga_location}
		exit 1
	fi

	${cbfstool} ${rom} add -f "${_vga_location}" \
	    -n "pci${CONFIG_VGA_BIOS_ID}.rom" \
	    -t optionrom || exit 1
}

inject_blob_smsc_sch5545_ec()
{
	rom="${1}"

	_sch5545ec_location="${CONFIG_SMSC_SCH5545_EC_FW_FILE#../../}"

	if [ ! -f "${_sch5545ec_location}" ]; then
		printf "SCH5545 firmware file missing\n" 1>&2
		exit 1
	fi

	"${cbfstool}" "${rom}" add -f "${_sch5545ec_location}" \
	    -n sch5545_ecfw.bin -t raw || exit 1
}

modify_gbe()
{
	printf "changing mac address in gbe to ${new_mac}\n"

	rom=${1}

	[ -z ${CONFIG_GBE_BIN_PATH} ] && \
		err "CONFIG_GBE_BIN_PATH not set"

	_gbe_location=${CONFIG_GBE_BIN_PATH#../../}

	[ -f "${_gbe_location}" ] || \
		err "CONFIG_GBE_BIN_PATH points to missing file"
	[ -f ${nvmutil} ] || \
		make -C util/nvmutil || err 'failed to build nvmutil'

	_gbe_tmp=$(mktemp -t gbeXXXX.bin)
	cp ${_gbe_location} ${_gbe_tmp}
	${nvmutil} "${_gbe_tmp}" setmac ${new_mac} || \
	    err 'failed to modify mac address'

	${ifdtool} -i GbE:${_gbe_tmp} "${rom}" -O "${rom}" || exit 1

	rm -f ${_gbe_tmp}
}

listboards()
{
	for boarddir in ${cbcfgsdir}/*; do
		[ -d "${boarddir}" ] || continue
		board="${boarddir##${cbcfgsdir}/}"
		board="${board%/}"
		printf '%s\n' "${board##*/}"
	done
}

usage()
{
	cat <<- EOF
	USAGE: ./update blobs inject -r [rom path] -b [boardname] -m [macaddress]
	Example: ./update blobs inject -r x230_12mb.rom -b x230_12mb

	Adding a macadress to the gbe is optional.
	If the [-m] parameter is left blank, the gbe will not be touched.

	Type './update blobs inject listboards' to get a list of valid boards
	EOF
}

main $@
