#!/usr/bin/env sh

#
#  helper script: update U-Boot configs (run make oldconfig)
#
#	Copyright (C) 2022 Alper Nebi Yasak <alpernebiyasak@gmail.com>
#	Copyright (C) 2022 Ferass El Hafidi <vitali64pmemail@protonmail.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# This script assumes that the working directory is the root
# of git or release archive

[ "x${DEBUG+set}" = 'xset' ] && set -v
set -u -e

printf "Updating U-Boot configs\n"

# Build ROM images for supported boards
updateconf() {
	board="$1"
	if [ -f "resources/u-boot/${board}/target.cfg" ]; then
        tree="undefined"
        . "resources/u-boot/${board}/target.cfg" # source
        if [ "${tree}" = "undefined" ]; then
            return 0
        fi
        if [ ! -d "u-boot/${tree}" ]; then
            ./fetch_trees u-boot ${tree}
        fi
        for ubcfg in resources/u-boot/${board}/config/*; do
            if [ ! -f ${ubcfg} ]; then
                continue
            fi
            (
                cd u-boot/${tree}/
                rm -f .config*
                make distclean
            )
            mv $ubcfg u-boot/${tree}/.config
            (
                cd u-boot/${tree}/
                make oldconfig
            )
            mv u-boot/${tree}/.config $ubcfg
            rm -f u-boot/${tree}/.config*
            (
                cd u-boot/${tree}/
                make distclean
            )
        done
    else
        printf "\nupdate/config/u-boot: no target.cfg for: %s\n" "${board}"
    fi
}

if [ $# -gt 0 ]; then
	for board in "${@}"; do
	    updateconf "${board}"
	done
else
	for board in resources/u-boot/*; do
        if [ ! -d "${board}" ]; then
            continue
        fi
	    updateconf "${board##*/}"
	done
fi

printf "\n\n"

