#!/usr/bin/env sh
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2023 Leah Rowe <leah@libreboot.org>

[ "x${DEBUG+set}" = 'xset' ] && set -v
set -u -e

. "include/err.sh"
. "include/make.sh"

eval "$(setvars "" mode project _flag codedir)"

# main() is in include/make.sh

handle_dependencies()
{
	[ $# -gt 0 ] && x_ ./handle make file ${_flag} ${@}

	[ -d "${project}" ] || x_ ./update project repo "${project%/*}"
	[ -d "${project}" ] || \
		err "handle_dependencies: ${project%/*} not downloaded"

	[ "${project}" = "uefitool" ] || return 0 # TODO: remove hardcoding
	(
	x_ cd uefitool
	cmake UEFIExtract/ || [ -f Makefile ] || \
	    err "handle_dependencies: !cmake UEFIExtract/"
	)
}

handle_targets()
{
	[ -f "${project}/Makefile" ] || [ -f "${project}/makefile" ] || \
	    [ -f "${project}/GNUmakefile" ] || return 0
	[ "${mode}" = "all" ] && x_ make -C "${project}" -j$(nproc) && return 0
	x_ make -C "${project}" clean
	make -C "${project}" distclean 2>/dev/null || :
}

main $@
